spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/legal_metrology
spring.datasource.username=root
spring.datasource.password=vikky@2008

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true